apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
        app: edinayasreda
        tier: backend
  template:
    metadata:
      labels:
        app: edinayasreda
        tier: backend
    spec:
      containers:
      - name: phpyii
        image: yagudinaleksandr/yii_server:v1
        env:
        - name: GET_HOSTS_FROM
          value: "dns"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80